### ISSUE TITLE
iOS

### ISSUE THREAD

**Issue by InSasquatchCountry** [connectdotz/obsidian-mov-support#1]
I can't seem to find it when I search within community plugins. Is there anything we can do to help you get approved? I think brew.sh has like a stars bar that has to be surpassed to be included. Is this something similar? I would like this for my phone.

**Comment by insasquatchcountry** [comment]
I was able to install it on my Mac and then it auto synced to my phone because i have my vault in iCloud 👍

**Comment by InSasquatchCountry** [comment]
so it seems that the iOS app already supports MOV but the video I was trying to include my note was maybe just too big and was crashing the app. I thought I had installed this plug-in but I actually get this error message when I try to enable it.

![image](https://github.com/connectdotz/obsidian-mov-support/assets/8946291/426a5bb1-4ace-453d-adea-5978d6eeb818)

**Comment by connectdotz** [comment]
yeah, you don't need this plugin. `.mov` is natively supported by Obsidian now.
